DELETE FROM `mangos_string` WHERE `entry` IN (11133,11134);
INSERT INTO `mangos_string` VALUES
(1700,'RAF system ok.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(1701,'RAF system error.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
