#ifndef __REVISION_SQL_H__
#define __REVISION_SQL_H__
 #define REVISION_DB_CHARACTERS "required_s2063_12562_01_characters_various_tables"
 #define REVISION_DB_MANGOS "required_s2138_12670_01_mangos_spell_template"
 #define REVISION_DB_REALMD "required_10008_01_realmd_realmd_db_version"
 #define REVISION_DB_CHARACTERS_DEV "required_dev_0004_01_character_dev_db_version"
 #define REVISION_DB_MANGOS_DEV "required_dev_0004_01_mangos_dev_db_version"
 #define REVISION_DB_REALMD_DEV "required_dev_0004_01_realmd_dev_db_version"
#endif // __REVISION_SQL_H__
